**420-C74-SF - Techniques d'apprentissage automatique - Automne 2026 - Spécialiste en solutions d'intelligence artificielle**<br/>
© 2026 MKL.AI - Tous droits réservés
<br/>
![Atelier - Régression linéaire multiple](static/04-A-banner.png)
<br/>
**Objectif:** cette séance de travaux pratique consiste en la mise en oeuvre sous forme de code vectorisé de l'**algorithme du gradient en régression linéaire multiple**. Le jeu de données utilisé sera la version complète du jeu de données *Advertising* et devra être **mis à l'échelle**

In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

### 0 - Chargement des bibliothèques

In [2]:
# Manipulation de données
import numpy as np
import pandas as pd
from collections import defaultdict

# Visualisation de données
import matplotlib.pyplot as plt
import seaborn as sns

# Outils divers
from tqdm.notebook import tqdm_notebook
from tqdm import tqdm

In [3]:
# Configuration de la visualisation
sns.set_theme(style="darkgrid", rc={'figure.figsize':(11.7,8.27)})

### 1 - Lecture du jeu de données advertising

**Exercice 1-1**: à l'aide de la bibiothèques *pandas*, lire le fichier `advertising-multivariate.csv`

In [4]:
# Compléter le code ci-dessous ~ 1 ligne
df = pd.read_csv("../../data/advertising-multivariate.csv")

**Exercice 1-2**: à l'aide de la fonction `head()`, visualiser les premières lignes de la trame de données. Quelle sera la taille du vecteur de paramètres $\theta$ ?

In [5]:
# Compléter le code ci-dessous ~ 1 ligne
df.head()

,Unnamed: 0,TV,radio,newspaper,sales
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9


### 2 - Mise à l'échelle des données

**Exercice 2**: Standardiser les données.<br/>
Note: Il n'est pas nécéssaire de standardiser la variable de sortie, mais vous pouvez le faire à des fins de simplification

In [ ]:
# Compléter le code ci-dessous ~ 1 ligne
df_norm =   (df - df.mean()) / df.std(ddof=0) #Directement avec Pandas.... il fait colonne par colonne!
df_norm.head()

,Unnamed: 0,TV,radio,newspaper,sales
0,-1.723412,0.969852,0.981522,1.778945,1.552053
1,-1.706091,-1.197376,1.082808,0.669579,-0.696046
2,-1.688771,-1.516155,1.528463,1.783549,-0.907406
3,-1.671450,0.052050,1.217855,1.286405,0.860330
4,-1.654129,0.394182,-0.841614,1.281802,-0.215683


### 3 - Préparation de la structure de données

**Exercice 3**: Construire la matrice des prédicteurs X sans oublier d'ajouter une colonne représentant $x_0$

In [ ]:
# Compléter le code ci-dessous ~ 5 lignes

x1 = df["TV"]
x2 = df["radio"]
x3 = df["newspaper"]
x0 = np.ones(len(df))

X = np.column_stack((
    x0,
    df["TV"].to_numpy(),
    df["radio"].to_numpy(),
    df["newspaper"].to_numpy()
))

print (X.shape)

y = df['sales'].values # Nous gardons ici les valeurs non standardisée

AttributeError: module 'numpy' has no attribute 'row_stack'

<strong style='color: green'>TEST - Le code ci-dessous vous permet de tester la forme de `X`. Le `assert` ne doit pas renvoyer d'exception</strong>

In [22]:
assert X.shape == (200,4)

### 4 - Définition du modèle

**Exercice 4**: compléter la fonction ci-dessous représentant le modèle de régression linéaire multiple (hypothèse)

Pour rappel, le modèle de régression multiple est

$h_{\theta}(x)=\theta_{0}x_0 + \theta_{1}x_1 + \cdots + \theta_{n}x_n = \theta^TX$

In [54]:
def hypothesis(x, theta):
    #assert x.shape[0] == theta.shape[0]
    
    h = np.dot( X, theta)
    
    return h

In [49]:
Z = hypothesis(X,np.array([1,2,3,4]).reshape(-1,1))

(200, 1)


<strong style='color: green'>TEST - Le code ci-dessous vous permet de tester votre fonction `hypothesis`. Le `assert` ne doit pas renvoyer d'exception</strong>

In [55]:
x_test = np.array([[1,1],[3,4],[2,2],[1,-1]])
theta_test = np.array([1,2,2,4]).reshape(-1,1)
print('--- x ---')
print(x_test)
print('--- theta --- ')
print(theta_test)
hypothesis(x_test, theta_test)
#assert np.array_equal(hypothesis(x_test,theta_test), np.array([15,9]))

--- x ---
[[ 1  1]
 [ 3  4]
 [ 2  2]
 [ 1 -1]]
--- theta --- 
[[1]
 [2]
 [2]
 [4]]


array([[ 813.6],
       [ 349. ],
       [ 404.4],
       [ 620.6],
       [ 617.8],
       [ 416.2],
       [ 275.6],
       [ 327. ],
       [  26.4],
       [ 490.6],
       [ 241.6],
       [ 494.4],
       [ 382.4],
       [ 240. ],
       [ 659. ],
       [ 698.8],
       [ 665.8],
       [ 866.2],
       [ 253.6],
       [ 419.8],
       [ 706.8],
       [ 580. ],
       [ 257.6],
       [ 596.2],
       [ 224. ],
       [ 611.8],
       [ 395.8],
       [ 606.2],
       [ 644.4],
       [ 337.4],
       [ 816.2],
       [ 416. ],
       [ 318.4],
       [ 573.4],
       [ 224.8],
       [ 624.6],
       [ 642.4],
       [ 432. ],
       [ 281. ],
       [ 660.4],
       [ 577. ],
       [ 576.6],
       [ 650.8],
       [ 537.2],
       [ 275.8],
       [ 522.2],
       [ 343. ],
       [ 637.8],
       [ 686.6],
       [ 305.4],
       [ 545.2],
       [ 235.4],
       [ 675.6],
       [ 693.4],
       [ 647.6],
       [ 737.6],
       [ 237.4],
       [ 378.2],
       [ 672.6

### 5 - Fonction de coût

**Exercice 5**: compléter la fonction ci-dessous permettant le calcul du coût (fonction de coût)

Pour rappel, la fonction de coût en régression linéaire multiple s'exprime sous la forme

$J(\theta)= \frac{1}{2m}\sum\limits_{i=1}^{m}(h_{\theta}(x^{(i)})-y^{(i)})^{2}=\frac{1}{2m}(y-X^t\theta)^T\times(y-X^t\theta)$

Remarque: comme le montre l'équation ci-dessus, il exite deux méthodes pour calculer la fonction de coût. Choisissez celle qui vous convient.<br/><em>Optionnel: faites l'autre méthode</em>

In [41]:
def cost_function(x,y, theta):
    # Compléter le code ~ 1-4 lignes
    m = len(y)

    y_hat = hypothesis(x, theta)
    errors = y - y_hat

    result = np.sum((y-y_hat)**2) / (2 * m)

    return result
    

<strong style='color: green'>TEST - Le code ci-dessous permet de tester la fonction `cost_function`. Celle-ci doit retourner un `numpy.float64`, c'est-à-dire un nombre et non tableau (array). Le `assert` ne doit pas renvoyer d'exception et le résultat attendu est ~ 94.92</strong>

In [43]:
theta_test = np.array([1,2,2,4]).reshape(-1,1)
cost = cost_function(X,y,theta_test)
assert type(cost) == np.float64


ValueError: shapes (1,4) and (200,4) not aligned: 4 (dim 1) != 200 (dim 0)

### 6 - Algorithme du gradient

**Exercice 6**: Compléter l'algorithme du gradient ci-dessous. Choisir le vecteur $\theta$ initial, la valeurs du **pas** ($\alpha$) et le **nombre d'itérations**. Un test de convergence ne sera pas utilisé ici.

$
\text{Répéter pendant n_iterations}
\{\\
\theta_{j}:= \theta_{j} - \alpha\frac{1}{m}\sum\limits_{i=1}^{m}(h_{\theta}(x^{(i)})-y^{(i)})\times x_{j}^{(i)}\quad\forall j
\\
\}
$

Ou sous forme vectorisée:

$
\text{Répéter pendant n_iterations}
\{\\
\theta:= \theta - \alpha\frac{1}{m}(\theta^TX-y)\times X
\\
\}
$

<strong>Vous êtes vivement encouragés à utiliser la forme vectorisée. Celle-ci est de toute façon plus simple à coder que la version non vectorisée !</strong>

In [ ]:
theta = None
alpha = None
n_iterations = None

m = y.shape[0]

history = defaultdict(list)

for i in tqdm(range(0, n_iterations)):
    
    # Compléter le code ~ 2 lignes
    None
      
    # Sauvegarde des valeurs intermédiaires de theta et du coût
    if i%50 == 0:
        cost = cost_function(X, y, theta)
        history['theta_0'].append(theta[0])
        history['theta_1'].append(theta[1])
        history['theta_2'].append(theta[2])
        history['theta_3'].append(theta[3])
        history['cost'].append(cost)
        
print(f'Theta = {theta}')

Les valeurs des paramètres $\theta_j$ devraient approcher

```[[14.0225    ]
 [ 3.92908869]
 [ 2.79906919]
 [-0.02259517]]```

### 7 - Interprétation des paramètres

**Exercice 7**: Interpréter les paramètres obtenus

### Fin de l'atelier